# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intuizi < Formula
  desc "Official Intuizi CLI, a single-binary client for the Intuizi API v2"
  homepage "https://intuizi.com"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.6/intuizi_0.1.6_darwin_amd64.tar.gz"
      sha256 "563f855ad3e08cb38c1fd0d34f8c505b307543c6c6c726f05097f9b031013afd"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.6/intuizi_0.1.6_darwin_arm64.tar.gz"
      sha256 "d72c28c89a612ab7ef705970b2a5568b80a9a9fb93e3ea5d5a74058f0eb302b8"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.6/intuizi_0.1.6_linux_amd64.tar.gz"
      sha256 "539105aa8a7922ee05af0e1fcc607ae64895b553e6c670dfb64c45b00a64c07a"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.6/intuizi_0.1.6_linux_arm64.tar.gz"
      sha256 "4452561363d1e1baf440605457a353c5c0fb11e6e5d1cf774f31aaad0f345c06"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/intuizi version")
  end
end
