# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intuizi < Formula
  desc "Official Intuizi CLI, a single-binary client for the Intuizi API v2"
  homepage "https://intuizi.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.0.2/intuizi_0.0.2_darwin_amd64.tar.gz"
      sha256 "aa4d2775e802f9b8ec631cdbb86f7e47b372d16bbd3da9db56e1e28a70c1def7"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.0.2/intuizi_0.0.2_darwin_arm64.tar.gz"
      sha256 "75ba2ea9cfe141db1d51f87e65bf6972c17e538395f2517deda9dfad4b58261c"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.0.2/intuizi_0.0.2_linux_amd64.tar.gz"
      sha256 "e0ed36273fc13a739c91937ad594841b01363171e4c1dd336cd24eb089648bb6"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.0.2/intuizi_0.0.2_linux_arm64.tar.gz"
      sha256 "1fc3ce70979b7e662ff153c665436ff994e65d009582445d7fcb86bfdfeb7887"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/intuizi version")
  end
end
