# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intuizi < Formula
  desc "Official Intuizi CLI, a single-binary client for the Intuizi API v2"
  homepage "https://intuizi.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.3/intuizi_0.1.3_darwin_amd64.tar.gz"
      sha256 "1ddb6f60841a74669d58cc930f67e437bd5b1f9c479e1017f5f72f33add6c043"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.3/intuizi_0.1.3_darwin_arm64.tar.gz"
      sha256 "d76b79aebdd0efe44618c15e92fe3dcd0415e0c3c8bebc75d2886d82eca2bd99"

      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.3/intuizi_0.1.3_linux_amd64.tar.gz"
      sha256 "4119bd546eb4930fdb7b3a4b47fe1539e4d759b40a4a45fd972b8a33af724a75"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intuizi/intuizi-cli/releases/download/v0.1.3/intuizi_0.1.3_linux_arm64.tar.gz"
      sha256 "45f53cf0687bcaad736f473c2280ea7de32627e8d582812c9532c82e00e470a6"
      define_method(:install) do
        bin.install "intuizi"
        generate_completions_from_executable(bin/"intuizi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/intuizi version")
  end
end
